export const foundationChineseData = [
    {
      rank: '1',
      name: 'apache/doris',
      value: '4307.26',
      rankDelta: 1,
      valueDelta: +100,
    },
    {
      rank: '2',
      name: 'openharmony/docs',
      value: '3277.69',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '3',
      name: 'openharmony/arkui_ace_engine',
      value: '2818.09',
      rankDelta: -1,
      valueDelta: -3,
    },
    {
      rank: '4',
      name: 'milvus-io/milvus',
      value: '2001.11',
      rankDelta: 3,
      valueDelta: -100,
    },
    {
      rank: '5',
      name: 'apache/flink',
      value: '1816.72',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '6',
      name: 'apache/shardingsphere',
      value: '1662.8',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '7',
      name: 'apache/ozone',
      value: '1281.57',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '8',
      name: 'apache/iotdb',
      value: '1265.72',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '9',
      name: 'openharmony/graphic_graphic_2d',
      value: '1239.6',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '10',
      name: 'apache/pulsar',
      value: '1227.93',
      rankDelta: 0,
      valueDelta: 0,
    },
  ]

  export const foundationGlobalData = [
    {
      rank: '1',
      name: 'kubernetes/kubernetes',
      value: '5374.14',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '2',
      name: 'apache/doris',
      value: '4307.26',
      rankDelta: 2,
      valueDelta: 3,
    },
    {
      rank: '3',
      name: 'apache/airflow',
      value: '3642.9',
      rankDelta: -1,
      valueDelta: -3,
    },
    {
      rank: '4',
      name: 'openharmony/docs',
      value: '3277.69',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '5',
      name: 'openharmony/arkui_ace_engine',
      value: '2818.09',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '6',
      name: 'nodejs/node',
      value: '2736.37',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '7',
      name: 'apache/spark',
      value: '2654.02',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '8',
      name: 'apache/arrow',
      value: '2219.95',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '9',
      name: 'apache/beam',
      value: '2188.52',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '10',
      name: 'apache/hudi',
      value: '2124.67',
      rankDelta: 0,
      valueDelta: 0,
    },
  ]

  export const cloudNative = [
    {
      rank: '1',
      name: 'grafana/grafana',
      value: '7134.37',
      rankDelta: 1,
      valueDelta: 100,
    },
    {
      rank: '2',
      name: 'llvm/llvm-project',
      value: '7049.62',
      rankDelta: -2,
      valueDelta: -220,
    },
    {
      rank: '3',
      name: 'kubernetes/kubernetes',
      value: '5374.14',
      rankDelta: 3,
      valueDelta: 300,
    },
    {
      rank: '4',
      name: 'ClickHouse/ClickHouse',
      value: '4941.99',
      rankDelta: -4,
      valueDelta: 400,
    },
    {
      rank: '5',
      name: 'cilium/cilium',
      value: '3215.42',
      rankDelta: 5,
      valueDelta: -500,
    },
    {
      rank: '6',
      name: 'ceph/ceph',
      value: '3172.49',
      rankDelta: -6,
      valueDelta: 600,
    },
    {
      rank: '7',
      name: 'keycloak/keycloak',
      value: '3095.56',
      rankDelta: 7,
      valueDelta: 700,
    },
    {
      rank: '8',
      name: 'gravitational/teleport',
      value: '3082.18',
      rankDelta: 0,
      valueDelta: 0,
    },
    {
      rank: '9',
      name: 'envoyproxy/envoy',
      value: '2929.08',
      rankDelta: 9,
      valueDelta: -900,
    },
    {
      rank: '10',
      name: 'backstage/backstage',
      value: '2903.39',
      rankDelta: 10,
      valueDelta: 100,
    },
  ]