# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish CI

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check if all secret exists
        run: |
          # 如果所有运行本 job 的 secrets 存在，则将 SECRETS_ALL_EXISTS 设为 true
          echo "SECRETS_ALL_EXISTS=${{ secrets.OSS_ACCESS_KEY_ID && secrets.OSS_ACCESS_KEY_SECRET && secrets.OSS_REGION && secrets.OSS_BUCKET && secrets.OSS_TARGET_PATH }}" >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v4
        if: ${{ env.SECRETS_ALL_EXISTS }}

      - uses: pnpm/action-setup@v4
        if: ${{ env.SECRETS_ALL_EXISTS }}
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        if: ${{ env.SECRETS_ALL_EXISTS }}
        with:
          node-version: '22'
          cache: 'pnpm'

      - run: pnpm i --frozen-lockfile
        if: ${{ env.SECRETS_ALL_EXISTS }}
      - run: pnpm build
        if: ${{ env.SECRETS_ALL_EXISTS }}
        env:
          CI: false

      - name: Publish to OSS
        uses: tvrcgo/upload-to-oss@master
        if: ${{ env.SECRETS_ALL_EXISTS }}
        with:
          key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          region: ${{ secrets.OSS_REGION }}
          bucket: ${{ secrets.OSS_BUCKET }}
          assets: |
            ./build/**:${{ secrets.OSS_TARGET_PATH }}
